# Generated by Django 3.0.6 on 2020-05-25 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.CharField(max_length=80, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=80)),
                ('user_head', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('title', models.CharField(max_length=80)),
                ('film_id', models.CharField(max_length=80, primary_key=True, serialize=False, unique=True)),
                ('film_url', models.URLField()),
                ('image_url', models.URLField()),
                ('play_count', models.IntegerField(default=0)),
                ('good_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dubweb.UserProfile')),
            ],
        ),
    ]
